/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Driver */

#ifndef _Included_Driver
#define _Included_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Driver
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Driver_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Driver
 * Method:    readMSAndBack
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Driver_readMSAndBack
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
